apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: votingapp
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: votingapp#{acr_env}#acr.azurecr.io/result:latest
        resources:
          limits:
            cpu: 200m
            memory: 128Mi       
        ports:
        - containerPort: 80
          name: result
      imagePullSecrets:
      - name: acr-secret