apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: votingapp
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: votingapp#{acr_env}#acr.azurecr.io/vote:latest
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret