apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: votingapp
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    apps: vote
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      name: vote-service
  selector:
    app: vote