apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: worker
  name: worker
  namespace: votingapp
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template: 
    metadata: 
      labels: 
        app: worker
    spec: 
      containers: 
      - image: votingapp#{acr_env}#acr.azurecr.io/worker:latest
        name: worker
        resources:
          limits:
            cpu: 200m
            memory: 128Mi