name: voting app deployment to AKS
on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: environment
        default: 'production' 
        options: 
        - dev
        - stage
        - production
 
permissions:
  id-token: write
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: install ansible
        run: |
          sudo pip3 install ansible
          curl -O https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
          sudo pip3 install -r requirements-azure.txt
      - name: show ansible version
        run: ansible --version
      - name: azure log in using OIDC
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: 'Run az commands'
        run: |
          az account show
          az group list
          pwd
      - name: Build and analysis
        env:
          resource_group: votingapp-${{ github.event.inputs.name.description }}-rg
          location: eastus
        run: ansible-playbook azure_infra_with_ansible/azure_create_aks.yml -e "ansible_python_interpreter=/usr/bin/python3 resource_group=$resource_group location=$location"